sonar.projectKey=hello-world-swiftui
sonar.projectName=Hello World SwiftUI
sonar.projectVersion=1.0
sonar.sources=.
# Excluimos carpetas que no son código fuente
sonar.exclusions=**/*.Tests/**, **/*.UITests/**

# Indicamos dónde estará el reporte de SwiftLint que generará GitHub Actions
sonar.swift.swiftlint.report=swiftlint.json