name: SonarQube iOS Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar-analysis:
    name: Build, Lint, Test, and Scan
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 

      - name: Install Dependencies (SwiftLint & Sonar Scanner)
        run: |
          brew install swiftlint
          brew install sonar-scanner

      # Ejecutar SwiftLint.
      - name: Run SwiftLint
        run: |
          swiftlint lint --reporter json > swiftlint.json || true

      # Ejecutar Tests y generar el .xcresult
      - name: Run Xcode Tests
        run: |
          # Limpiar compilaciones anteriores
          rm -rf build/
          
          # xcodebuild ejecuta los tests y genera el Test-Result.xcresult
          xcodebuild clean test \
            -project hello_word_swiftui.xcodeproj \
            -scheme "hello_word_swiftui" \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=latest" \
            -enableCodeCoverage YES \
            -resultBundlePath build/Test-Result.xcresult
        continue-on-error: true

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.host.url="${SONAR_HOST_URL}" \
            -Dsonar.token="${SONAR_TOKEN}"